In [2]:
import pandas as pd
data = {'Name':['Alice','Bob'],'Age':[23,25]}
pd.DataFrame(data)

    Name  Age
0  Alice   23
1    Bob   25

In [3]:
lst_2=[['Dan','M',26],['Riya','F',24]]
df_2=pd.DataFrame(lst_2,columns=['Name','Gender','Age',])

In [4]:
lst=[['Alice','23'],['Bob','25']]
df = pd.DataFrame(lst,columns=['Name','Age'])
print(df)

    Name Age
0  Alice  23
1    Bob  25

In [5]:
df.head()

    Name Age
0  Alice  23
1    Bob  25

In [7]:
df.tail()

    Name Age
0  Alice  23
1    Bob  25

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      str
dtypes: str(2)
memory usage: 164.0 bytes

In [9]:
df.describe()

         Name Age
count       2   2
unique      2   2
top     Alice  23
freq        1   1

In [11]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [12]:
df[['Name','Age']]

    Name Age
0  Alice  23
1    Bob  25

In [13]:
df.loc[0]

Name    Alice
Age        23
Name: 0, dtype: str

In [14]:
df.loc[1]

Name    Bob
Age      25
Name: 1, dtype: str

In [15]:
df.iloc[1]

Name    Bob
Age      25
Name: 1, dtype: str

In [53]:
df[df['Age'] > 24]

  Name Gender  Age
1  Bob      M   25

In [6]:
df['Gender']=['F','M']

In [67]:
df.head()

    Name Gender
0  Alice      F
1    Bob      M

In [71]:
df.drop('Age',axis=1,inplace=True)

In [32]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [61]:
df.dropna

<bound method DataFrame.dropna of     Name Gender
0  Alice      F
1    Bob      M>

In [36]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [10]:
df['Age']=pd.to_numeric(df['Age'])

In [11]:
df_2['Age']=pd.to_numeric(df_2['Age'])

In [70]:
df.groupby('Gender')['Age'].mean()

Gender
F    23.0
M    25.0
Name: Age, dtype: float64

In [72]:
df['Age']=['23','25']

In [39]:
df.head()

    Name Gender Age
0  Alice      F  23
1    Bob      M  25

In [79]:
print(df_2)

   Name Gender  Age
0   Dan      M   26
1  Riya      F   24

In [77]:
pd.merge(df,df_2,on='Gender')

  Name_x Gender Age_x Name_y  Age_y
0  Alice      F    23   Riya     24
1    Bob      M    25    Dan     26

In [80]:
df.join(df_2)

ValueError: columns overlap but no suffix specified: Index(['Name', 'Gender', 'Age'], dtype='str')

In [81]:
df=pd.read_csv('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [7]:
df.sort_values('Age')

    Name Age Gender
0  Alice  23      F
1    Bob  25      M

In [83]:
df.to_csv('output.csv',index=False)

In [12]:
df['Age'].apply(lambda x:x+1)

0    24
1    26
Name: Age, dtype: int64

In [13]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str